language: python
python:
  - "2.7"

env:
    - SHOTGUN_EXTERNAL_REPOS_ROOT=/tmp

# command to install dependencies
# Ideally we would be pip installing tk-core, but we need the testing framework from core,
# so we will clone the repo install to a known location and run the tests there.
install:
    - pip install -r tests/ci_requirements.txt
    - git clone --depth 1 --branch SG-7259_json_and_context_utils https://github.com/shotgunsoftware/tk-core /tmp/tk-core
    - git clone --depth 1 --branch master https://github.com/shotgunsoftware/tk-framework-qtwidgets /tmp/tk-framework-qtwidgets
    - git clone --depth 1 --branch master https://github.com/shotgunsoftware/tk-framework-shotgunutils /tmp/tk-framework-shotgunutils
    - git clone --depth 1 --branch master https://github.com/shotgunsoftware/tk-shell /tmp/tk-shell
    # install pyside - from https://stackoverflow.com/questions/24489588
    - sudo apt-get install libqt4-dev
    - pip install PySide --no-index --find-links https://parkin.github.io/python-wheelhouse/;
    # Travis CI servers use virtualenvs, so we need to finish the install by the following
    - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install
    # Now we need to start the X server...
    # Taken from: https://github.com/colmap/colmap/commit/606d3cd09931d78a3272f99b5e7a2cb6894e243e
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
    # Finally, tell Qt to run offscreen.
    - export QT_QPA_PLATFORM=offscreen

# command to run tests
script: tests/run_tests.sh --with-coverage
after_success: coveralls
